import chromadb
from helper import pretty_print

client = chromadb.Client()
collection = client.create_collection("multiple_topics")


docs = {
    "Quantum Entanglement": """A Window into the Subatomic World
Quantum entanglement, a phenomenon predicted by quantum mechanics, allows particles to become interconnected in such a way that the state of one particle instantly influences the state of another, no matter the distance between them. This "spooky action at a distance," as Einstein famously described it, has been experimentally verified and forms the basis of emerging technologies like quantum computing and quantum cryptography. Entanglement challenges our classical understanding of separateness and locality, suggesting a deeper level of interconnectedness in the fabric of reality. Researchers continue to explore its potential applications, hoping to revolutionize fields from secure communication to simulation of complex systems.""",
    "Dark Matter": """The Invisible Mass Shaping Our Universe
Dark matter constitutes about 27% of the universe's mass-energy content, yet it remains undetected by conventional means. Unlike ordinary matter, dark matter doesn't emit, absorb, or reflect light, making it invisible and detectable only through its gravitational effects. Its presence is inferred from galaxy rotation curves and gravitational lensing, where its mass bends light from distant stars. Current theories suggest it might be composed of exotic particles such as WIMPs (Weakly Interacting Massive Particles) or axions. Unraveling the mystery of dark matter is crucial for understanding the universe's structure, evolution, and ultimate fate, driving ongoing experiments in deep underground laboratories and space observatories.""",
    "The Higgs Boson": """Unlocking the Secrets of Mass
Discovered in 2012 at CERN's Large Hadron Collider, the Higgs boson is a fundamental particle associated with the Higgs field, which gives mass to other particles. Its discovery confirmed the last missing piece of the Standard Model of particle physics, earning the 2013 Nobel Prize in Physics for François Englert and Peter Higgs. The Higgs mechanism explains how particles acquire mass through their interaction with the omnipresent Higgs field. This discovery not only enhances our understanding of the universe's fundamental structure but also opens new avenues for exploring physics beyond the Standard Model, including the nature of dark matter and the unification of forces.""",
    "Gravitational Waves": """Ripples in the Fabric of Spacetime
Gravitational waves, first predicted by Albert Einstein in 1916, are ripples in spacetime caused by massive accelerating objects, such as merging black holes or neutron stars. These waves travel at the speed of light, carrying information about their origins and the nature of gravity itself. The first direct detection of gravitational waves by the LIGO and Virgo collaborations in 2015 marked a groundbreaking achievement, confirming a major prediction of Einstein's General Theory of Relativity and opening a new era of observational astronomy. By studying gravitational waves, scientists can probe the most extreme environments in the universe, test fundamental physics, and potentially uncover new astrophysical phenomena.""",
    "Gravitational Waves": """Ripples in the Fabric of Spacetime
Gravitational waves, first predicted by Albert Einstein in 1916, are ripples in spacetime caused by massive accelerating objects, such as merging black holes or neutron stars. These waves travel at the speed of light, carrying information about their origins and the nature of gravity itself. The first direct detection of gravitational waves by the LIGO and Virgo collaborations in 2015 marked a groundbreaking achievement, confirming a major prediction of Einstein's General Theory of Relativity and opening a new era of observational astronomy. By studying gravitational waves, scientists can probe the most extreme environments in the universe, test fundamental physics, and potentially uncover new astrophysical phenomena.""",
    "DNA": """The Blueprint of Life
Deoxyribonucleic acid (DNA) is the molecule that carries the genetic instructions for all living organisms. Comprised of two strands forming a double helix, DNA contains sequences of four nucleotides (adenine, thymine, cytosine, and guanine) that encode the information necessary for the development, functioning, growth, and reproduction of organisms. The Human Genome Project, completed in 2003, mapped the entire human genome, revealing about 20,000-25,000 genes. This monumental achievement has paved the way for advances in genetic research, personalized medicine, and our understanding of evolutionary biology.""",
    "Photosynthesis": """Converting Light into Life
Photosynthesis is the process by which green plants, algae, and certain bacteria convert light energy into chemical energy, producing oxygen and glucose from carbon dioxide and water. This process occurs in chloroplasts, using the green pigment chlorophyll to capture light energy. Photosynthesis is fundamental to life on Earth, providing the primary source of energy for nearly all organisms and playing a crucial role in regulating atmospheric oxygen and carbon dioxide levels. It is the foundation of food chains and ecosystems, supporting life across the planet.""",
    "The Human Microbiome": """Our Invisible Ecosystem
The human microbiome consists of trillions of microorganisms, including bacteria, viruses, fungi, and archaea, living in and on our bodies. These microbes outnumber human cells and are essential for various bodily functions, such as digestion, immune response, and even mental health. The gut microbiome, in particular, plays a crucial role in breaking down food, producing vitamins, and protecting against harmful pathogens. Research into the microbiome has revealed its significant impact on health and disease, highlighting the potential for microbiome-targeted therapies to treat conditions ranging from inflammatory bowel disease to obesity and depression.""",
    "CRISPR": """Revolutionizing Genetic Engineering
CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) is a revolutionary gene-editing technology that allows scientists to precisely alter DNA sequences and modify gene function. Discovered in bacteria as a defense mechanism against viruses, CRISPR-Cas9 has been adapted for use in genetic research and biotechnology. This tool enables targeted gene editing, offering potential treatments for genetic disorders, cancer, and infectious diseases. CRISPR's precision and efficiency have transformed molecular biology, opening new possibilities for advancements in medicine, agriculture, and synthetic biology.""",
    "Evolution": """The Unifying Theory of Biology
Evolution, the process by which species change over time through natural selection and genetic variation, is the fundamental concept that unifies all of biology. First proposed by Charles Darwin and Alfred Russel Wallace in the mid-19th century, the theory of evolution explains the diversity of life and the adaptation of organisms to their environments. Fossil records, comparative anatomy, and molecular biology provide robust evidence for evolutionary processes. Understanding evolution helps scientists interpret biological phenomena, trace the ancestry of species, and study the mechanisms driving genetic diversity and speciation.""",
    "Periodic Table": """Organizing the Elements
The periodic table is a systematic arrangement of chemical elements based on their atomic number, electron configuration, and chemical properties. Dmitri Mendeleev is credited with creating the first widely recognized periodic table in 1869, organizing elements into rows (periods) and columns (groups) based on recurring trends in their properties. The periodic table serves as a fundamental tool in chemistry, predicting the behavior of elements and guiding the development of materials, medicines, and technologies.""",
    "Chemical Bonds": """Connecting Atoms
Chemical bonds are interactions that hold atoms together in molecules and compounds. Covalent bonds involve the sharing of electron pairs between atoms, forming stable structures such as water (H2O) and methane (CH4). Ionic bonds result from the transfer of electrons between atoms, creating ions that attract each other due to their opposite charges, as seen in table salt (NaCl). Hydrogen bonds, weaker than covalent or ionic bonds, occur between molecules with hydrogen atoms bonded to electronegative atoms like oxygen or nitrogen, contributing to the properties of water and DNA.""",
    "Acids and Bases": """Fundamental Chemical Reactions
Acids and bases are essential classes of chemicals that undergo reactions to produce salts and water. Acids release hydrogen ions (H+) when dissolved in water, lowering pH values and reacting with bases to form salts. Strong acids like hydrochloric acid (HCl) are highly dissociated in water, while weak acids like acetic acid (found in vinegar) dissociate partially. Bases, such as sodium hydroxide (NaOH), release hydroxide ions (OH−) in water, increasing pH values and reacting with acids. Understanding acid-base reactions is crucial in fields from environmental science to industrial processes.""",
    "Chemical Reactions": """Transforming Matter
Chemical reactions involve the rearrangement of atoms to form new substances with different chemical compositions and properties. Reactants are substances that undergo change, while products are the resulting substances. Types of reactions include synthesis (combining substances, like A + B → AB), decomposition (breaking down substances, like AB → A + B), combustion (reacting with oxygen, like hydrocarbons + oxygen → carbon dioxide + water), and redox (electron transfer, like oxidation of iron). Chemical reactions underpin everyday processes from digestion to combustion engines and are fundamental to fields like materials science and pharmaceuticals.""",
    "Green Chemistry": """Sustainable Practices
Green chemistry aims to design chemical products and processes that minimize environmental impact, conserve resources, and reduce toxicity. Principles include using renewable feedstocks, designing safer chemicals and processes, minimizing waste generation, and using energy-efficient methods. Applications range from biodegradable plastics and cleaner manufacturing processes to sustainable agriculture and alternative energy sources. As concerns about climate change and pollution grow, green chemistry plays a crucial role in developing sustainable solutions for a more environmentally friendly future.""",
}

collection.add(
    documents=list(docs.values()),
    ids=list(docs.keys()),
)


result = collection.query(
    query_texts=["How are atoms made?"],
    n_results=2,
)

print(pretty_print(result))
